<?php
/**
 * @copyright Copyright (c) 2014 WebPT, INC
 */
use SignatureModule\Pad\SignatureAsset;

$this->headTitle('Signature Pad');
$this->headTitle()->setSeparator(' - ');

$this->headScript()->appendFile( 'https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js'  );
$this->scriptFile()->appendFile( $this->basePath( 'signature/js/assets/json2.min.js' ) );
$this->scriptFile()->appendFile( $this->basePath( 'signature/js/jquery.signaturepad.js' ) );
$this->scriptFile()->appendFile( $this->basePath( 'signature/js/assets/flashcanvas.js'), 'text/javascript', array('conditional' => 'lt IE 9'));

$this->scriptFile()->appendScript("
    $(document).ready(function() {
        $('.sigPad').signaturePad();
    });
");

$this->styleFile()->appendStylesheet( $this->basePath( 'signature/js/assets/jquery.signaturepad.css' ) );

?>
<form method="post" action="<?php echo $this->basePath('signature/pad/save'); ?>" class="sigPad">
    <label for="name">Print your name</label>
    <input type="text" name="name" id="name" class="name">
    <p class="typeItDesc">Review your signature</p>
    <p class="drawItDesc">Draw your signature</p>
    <ul class="sigNav">
        <li class="typeIt"><a href="#type-it" class="current">Type It</a></li>
        <li class="drawIt"><a href="#draw-it" >Draw It</a></li>
        <li class="clearButton"><a href="#clear">Clear</a></li>
    </ul>
    <div class="sig sigWrapper">
        <div class="typed"></div>
        <canvas class="pad"
                width="<? echo SignatureAsset::WIDTH - 2;?>"
                height="<? echo SignatureAsset::HEIGHT -2;?>">
        </canvas>
        <input type="hidden" name="output" class="output">
    </div>
    <button type="submit">Save Signature</button>
</form>