<?php
/**
 * @copyright Copyright (c) 2014 WebPT, INC
 */
$this->headTitle('Signature Pad');
$this->headTitle()->setSeparator(' - ');

$this->headScript()->appendFile( 'https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js'  );
$this->headScript()->appendFile( $this->basePath( 'signature/js/assets/json2.min.js' ) );
$this->headScript()->appendFile( $this->basePath( 'signature/js/jquery.signaturepad.js' ) );
$this->headScript()->appendFile( $this->basePath( 'signature/js/assets/flashcanvas.js'), 'text/javascript', array('conditional' => 'lt IE 9'));
$this->styleFile()->appendStylesheet( $this->basePath( 'signature/js/assets/jquery.signaturepad.css' ) );
?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('WebPT - Signature') ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <?php echo $this->headScript(); ?>
    <?php echo $this->styleFile(); ?>
    <?php echo $this->headLink(); ?>
</head>
<body>
<?php

    // Print page contents
    echo $this->content;

?>
</body>